# /bin/bash
#
# Author: Ashley Cawley // @ashleycawley // ash@ashleycawley.co.uk
#
# This script tests a list of websites to see if they have a security.txt
# file present on their website. If they do it downloads the message and
# saves it into a file labelled as their domain name.
#
# For more information on what that file is about see: https://securitytxt.org/
#
# Static Variables
SITELIST="site-list.txt" # Reads a list of sites from a file
SECURITY=/.well-known/security.txt
#
# Creating the folder to contain the results
mkdir -p ./results/
# Specifying a list of domains to be tested...
for domain in $(cat $SITELIST)
	do
	wget -nv $domain$SECURITY -O ./results/$domain
	echo "Status Code: $?"
	echo "" && sleep 2

# Deleting any empty files generated by wget that contain no results
find ./results/ -size 0 -print0 | xargs -0 rm 2>/dev/null
done
exit 0
